#cloud-config

coreos:
    units:
      - name: etcd.service
        command: start
      - name: mnt-zfspool.mount
        command: start
        content: |
          [Mount]
          What=192.168.10.10:/mnt/zfspool
          Where=/mnt/zfspool
          Type=nfs
